### ISSUE TITLE
Parsing gives an error

### ISSUE THREAD

**Issue by sarves** [UppsalaNLP/uuparser#27]
Hi, I get the following error when try to parse sentence:

sarves@Kanani:~/Documents/PhDDoc-GDrive/My-Syntactic Parsing/syntactic constructions/Dependency Grammar Based Structure$ uuparser --predict --outdir . --modeldir uuparser-ta-te-model --datadir UD_Tamil-TTB --model barchybrid.model --testfile UD_Tamil-Thamizhi/ta_thamizhi-ud-dev.conllu --ext-char-emb-file uuparser-ta-te-model/ta.vectors.xz 
[uuparser] 2021-02-06T00:45:05 INFO: Working with a transition-based parser
[uuparser] 2021-02-06T00:45:05 INFO: Reading params from uuparser-ta-te-model/params.pickle
[dynet] random seed: 3704109196
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
[uuparser] 2021-02-06T00:45:05 INFO: Loading model from uuparser-ta-te-model/barchybrid.model
[uuparser] 2021-02-06T00:45:06 INFO: Reading UD_Tamil-Thamizhi/ta_thamizhi-ud-dev.conllu
[uuparser] 2021-02-06T00:45:06 INFO: Time: 0.34s
[uuparser] 2021-02-06T00:45:06 INFO: Extracting embeddings from uuparser-ta-te-model/ta.vectors.xz
[uuparser] 2021-02-06T00:46:37 INFO: Time: 91s
[uuparser] 2021-02-06T00:46:37 INFO: Reading UD_Tamil-Thamizhi/ta_thamizhi-ud-dev.conllu
Traceback (most recent call last):       
  File "/usr/local/bin/uuparser", line 8, in <module>
    sys.exit(main())
  File "/home/sarves/.local/lib/python3.8/site-packages/uuparser/parser.py", line 325, in main
    run(experiment,options)
  File "/home/sarves/.local/lib/python3.8/site-packages/uuparser/parser.py", line 127, in run
    pred = list(parser.Predict(experiment.treebanks,"test",stored_opt))
  File "/home/sarves/.local/lib/python3.8/site-packages/uuparser/arc_hybrid.py", line 292, in Predict
    self.feature_extractor.getWordEmbeddings(conll_sentence, False, options, test_embeddings)
  File "/home/sarves/.local/lib/python3.8/site-packages/uuparser/feature_extractor.py", line 195, in getWordEmbeddings
    root.vecs["treebank"] = self.treebank_lookup[self.treebanks[treebank_id]]
KeyError: None

Just yo give you a background, I tried a multilingual parser without any problem. However, when I try to parse, I get the above error. I used fasttext char embedding. 

What could be the reason?

**Comment by LoicGrobol** [comment]
That's because you have a multilingual parser, but it doesn't know which treebank embedding it should be using.  You can give it a treebank embeddings from those you trained it with using the `--forced-tbank-emb` option.

**Comment by sarves** [comment]
Thank you, it did parse with the --forced-tbank-emb (command I used is this: _uuparser --predict --outdir . --modeldir uuparser-ta-te-model --datadir UD_Tamil-TTB --model barchybrid.model --testfile UD_Tamil-Thamizhi/ta_thamizhi-ud-dev.conllu --forced-tbank-emb=ta_thamizhi_)
out.conllu has the parsed text. However, out.conllu.txt empty.

Process also ends with the following error:

Traceback (most recent call last):
  File "/home/sarves/.local/lib/python3.8/site-packages/uuparser/utils/evaluation_script/conll17_ud_eval.py", line 220, in load_conllu
    head_id = int(columns[HEAD])
ValueError: invalid literal for int() with base 10: '_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sarves/.local/lib/python3.8/site-packages/uuparser/utils/evaluation_script/conll17_ud_eval.py", line 506, in <module>
    main()
  File "/home/sarves/.local/lib/python3.8/site-packages/uuparser/utils/evaluation_script/conll17_ud_eval.py", line 484, in main
    evaluation = evaluate_wrapper(args)
  File "/home/sarves/.local/lib/python3.8/site-packages/uuparser/utils/evaluation_script/conll17_ud_eval.py", line 457, in evaluate_wrapper
    gold_ud = load_conllu_file(args.gold_file)
  File "/home/sarves/.local/lib/python3.8/site-packages/uuparser/utils/evaluation_script/conll17_ud_eval.py", line 453, in load_conllu_file
    return load_conllu(_file)
  File "/home/sarves/.local/lib/python3.8/site-packages/uuparser/utils/evaluation_script/conll17_ud_eval.py", line 222, in load_conllu
    raise UDError("Cannot parse HEAD '{}'".format(columns[HEAD]))
__main__.UDError: Cannot parse HEAD '_'
Traceback (most recent call last):
  File "/home/sarves/.local/bin/uuparser", line 8, in <module>
    sys.exit(main())
  File "/home/sarves/.local/lib/python3.8/site-packages/uuparser/parser.py", line 325, in main
    run(experiment,options)
  File "/home/sarves/.local/lib/python3.8/site-packages/uuparser/parser.py", line 135, in run
    score = utils.evaluate(treebank.test_gold,treebank.outfilename,options.conllu)
  File "/home/sarves/.local/lib/python3.8/site-packages/uuparser/utils.py", line 433, in evaluate
    subprocess.run(["python", str(UTILS_PATH/"evaluation_script/conll17_ud_eval.py"), "-v", "-w", str(UTILS_PATH/"evaluation_script/weights.clas"), gold, test], stdout=scoresfile_stream, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '/home/sarves/.local/lib/python3.8/site-packages/uuparser/utils/evaluation_script/conll17_ud_eval.py', '-v', '-w', '/home/sarves/.local/lib/python3.8/site-packages/uuparser/utils/evaluation_script/weights.clas', 'UD_Tamil-Thamizhi/ta_thamizhi-ud-dev.conllu', './out.conllu']' returned non-zero exit status 1.

What could be the reason?

**Comment by LoicGrobol** [comment]
It probably means that there is a line with "_" in the first column in either your input or your output file. Also I don't think we are supposed to write to out.conllu.txt? It's been a long time since I touched this part of the code, I'll have a look.

**Comment by mdelhoneux** [comment]
Ack, sorry that I only see this! I don't know why I don't get notifications for this anymore. I will try to change that.
At first sight, I think this might be an incompatibility in the options where you specify both testfile and datadir? I would try specifying only one of the two?
